--[[
    GRF Editor [Version - 1.8.3.8]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

dofile("System/iteminfo2.lub") 

main = function()
	for ItemID, DESC in pairs(tbl) do
		result, msg = AddItem(ItemID, DESC.identifiedDisplayName, DESC.identifiedResourceName, DESC.identifiedDisplayName, DESC.identifiedResourceName, DESC.slotCount, DESC.ClassNum)
		if not result == true then
			return false, msg
		end
		-- prepend item id to description
		res, m = AddItemIdentifiedDesc(ItemID, "^6666CCItemID: " .. tostring(ItemID) .. "^000000")
		if not res then
			return false, m
		end
		for k, v in pairs(DESC.identifiedDescriptionName) do
			result, msg = AddItemUnidentifiedDesc(ItemID, v)
			if not result == true then
				return false, msg
			end
		end
		for k, v in pairs(DESC.identifiedDescriptionName) do
			result, msg = AddItemIdentifiedDesc(ItemID, v)
			if not result == true then
				return false, msg
			end
		end
				
		k = DESC.identifiedResourceName
		v = DESC.identifiedDisplayName
	end
	
	return true, "good"
end
