customsprites = {
    --[[
    ! YOU DO NOT HAVE TO RE-RUN iteminfo.bat AFTER EDITING THIS FILE !
    ! Sprites added here will take priority over original iteminfo !
	
	Format:
	[item ID] = "appearance sprite/resource name",
	
	You can find sprite/resource names in iteminfo.lub or ratemyserver.net
	--]]
	
	-- Misc
	[22511] = "빛의주문서", -- Fenrir's Power Scroll -> Scroll sprite
	[4557]	= "카프라명함", -- Weakened Fenrir Card -> Kafra Card sprite
	[6187]  = "스페어카드", -- Blank Card -> Spare Card sprite

	-- MVP Cards (Own Card Design)
	[27164] = "카드fwq", -- Faceworm Queen Card
	[4662] = "카드ber", -- Big Eggring Card
	[4143] = "카드orchero", -- Orc Hero Card
	[4146] = "카드maya", -- Maya Card
	[4135] = "카드orclord", -- Orc Lord Card
	[4128] = "카드gtb", -- Golden Thief Bug Card
	[4123] = "카드eddga", -- Eddga Card
	[4144] = "카드osiris", -- Osiris Card
	[4236] = "카드amonra", -- Amon Ra Card
	[4121] = "카드phreeoni", -- Phreeoni Card
	[4134] = "카드dracula", -- Dracula Card
	[4142] = "카드doppel", -- Doppelganger Card
	[4132] = "카드mistress", -- Mistress Card
	[4131] = "카드flower", -- Moonlight Flower Card
	[4376] = "카드tanee", -- Lady Tanee Card
	[4147] = "카드bapho", -- Baphomet Card
	[4148] = "카드pharaoh", -- Pharaoh Card
	[4451] = "카드crothen", -- Entweihen Crothen Card
	[4137] = "카드drake", -- Drake Card
	[4318] = "카드sk", -- Stormy Knight Card
	[27126] = "카드boitata", -- Boitata Card
	[4276] = "카드lotd", -- Lord of the Dead Card
	[4520] = "카드leak", -- Leak Card
	[4534] = "카드octopus", -- Giant Octopus Card
	[4168] = "카드dl", -- Dark Lord Card
	[27162] = "카드gopinich", -- Gopinich Card
	[4372] = "카드wlady", -- White Lady Card
	[4324] = "카드hatii", -- Hatii Card
	[4419] = "카드ktullanux", -- Ktullanux Card
	[4399] = "카드mot", -- Memory of Thanatos Card
	[4457] = "카드seiger", -- Naght Seiger Card
	[4263] = "카드samurai", -- Samurai Specter Card
	[4342] = "카드rsx", -- RSX-0806 Card
	[4527] = "카드darkfish", -- Dark Coelacanth Card
	[4526] = "카드weirdfish", -- Weird Coelacanth Card
	[27025] = "카드deadking", -- Dead King Card
	[27326] = "카드morrocm", -- Morocc's Minion Card
	[4330] = "카드esl", -- Evil Snake Lord Card
	[4651] = "카드itgk", -- Infinite Tao Gunka Card
	[4648] = "카드ieddga", -- Infinite Eddga Card
	[4647] = "카드iosiris", -- Infinite Osiris Card
	[4649] = "카드iphreeoni", -- Infinite Phreeoni Card
	[4650] = "카드iorchero", -- Infinite Orc Hero Card
	[4305] = "카드tgr", -- Turtle General Card
	[4302] = "카드tgk", -- Tao Gunka Card
	[27151] = "카드evil", -- Evil Card
	[27150] = "카드tec", -- Toxic Enhancement Chimera Card
	[27329] = "카드cks", -- Cursed King Schmidt Card
	[4425] = "카드atroce", -- Atroce Card
	[4636] = "카드bijou", -- Bijou Card
	[27318] = "카드miguel", -- Miguel Card
	[4456] = "카드nyd", -- Nidhoggur Shadow Card
	[27081] = "카드angryflower", -- Angry Moonlight Flower Card
	[27305] = "카드elat", -- EL-A17T Card
	[27152] = "카드cutie", -- Cutie Card
	[4525] = "카드kraken", -- Kraken Card
	[4403] = "카드kiel", -- Kiel-D-01 Card
	[4374] = "카드vesper", -- Vesper Card
	[27182] = "카드ferlock", -- Captain Ferlock Card
	[4386] = "카드detale", -- Detardeurus Card
	[27113] = "카드aktullanux", -- Awakened Ktullanux Card
	[4441] = "카드fhb", -- Fallen Bishop Card
	[300079] = "카드gp", -- Red Pepper Card
	[300107] = "카드meow", -- Meow Card
	[4408] = "카드gun", -- Gloom Under Night Card
	[27104] = "카드adracula", -- Angry Dracula Card
	[300078] = "카드sweetie", -- Sweetie Card
	[4507] = "카드qs", -- Queen Scaraba Card
	[4509] = "카드gqs", -- Gold Queen Scaraba Card
	[27106] = "카드aferre", -- Awakened Ferre Card
	[4352] = "카드egnigem", -- Boss Egnigem Card
	[4407] = "카드randris", -- Randgris Card
	[4578] = "카드pyuriel", -- Pyuriel Card
	[4574] = "카드daehyon", -- Daehyon Card
	[4580] = "카드kades", -- Kades Card
	[4652] = "카드nar", -- Nightmare Amon Ra Card
	[4697] = "카드charleston", -- Charleston Card
	[300099] = "카드spapilia", -- Silva Papilia Card
	[4430] = "카드ifrit", -- Ifrit Card
	[4576] = "카드gioia", -- Gioia Card
	[4145] = "카드beelze", -- Beelzebub Card
	[4603] = "카드croot", -- Corruption Root Card
	[4601] = "카드amdarais", -- Amdarais Card
	[4592] = "카드buwaya", -- Buwaya Card
	[27265] = "카드evilfan", -- Evil Fanatics Card
	[4528] = "카드mutantfish", -- Mutant Coelacanth Card
	[4529] = "카드cruelfish", -- Cruel Coelacanth Card
	[27180] = "카드mechaspider", -- Mechaspider Card
	[27327] = "카드grimreaper", -- Grim Reaper Ankou Card
	[4357] = "카드lk", -- Lord Knight Card
	[4359] = "카드sinx", -- Assassin Cross Card
	[4361] = "카드ws", -- Mastersmith Card
	[4363] = "카드hp", -- High Priest Card
	[4367] = "카드sniper", -- Sniper Card
	[4365] = "카드hw", -- High Wizard Card
	[4565] = "카드paladin", -- Paladin Card
	[4563] = "카드creator", -- Creator Card
	[4561] = "카드professor", -- Professor Card
	[4562] = "카드champion", -- Champion Card
	[4564] = "카드stalker", -- Stalker Card
	[4560] = "카드clown", -- Clown Card
	[4566] = "카드gypsy", -- Gypsy Card
	[4556] = "카드fenrir", -- Fenrir Card
	[31023] = "카드kimi", -- Celine Kimi Card
	[4610] = "카드sarah", -- Sarah Card
	[31026] = "카드sjew", -- Stephen Jack Ernest Wolf Card
	[27287] = "카드shinybear", -- Shiny Teddy Bear Card
	[27020] = "카드two", -- T W O Card
	[27119] = "카드otgr", -- Ominous Turtle General Card
	[27294] = "카드atgk", -- Ancient Tao Gunka Card
	[27298] = "카드awd", -- Ancient Wootan Defender Card
	[4625] = "카드th", -- Time Holder Card
	[27319] = "카드rbestia", -- R48-85-BESTIA Card
	[27321] = "카드dgm", -- Despair God Morocc Card
	[300239] = "카드smaya", -- Silent Maya Card
	[27334] = "카드cbapho", -- Chaotic Baphomet Card
	[4602] = "카드handarais", -- Amdarais H Card
	[4604] = "카드hcroot", -- Corruption Root H Card
	[300266] = "카드swordman", -- Unknown Swordsman Card
	[300080] = "카드grp", -- Great Red Pepper Card
	[300227] = "카드schulang", -- Schulang Card
	[300228] = "카드twisted", -- Twisted God Card
	[4681] = "카드flamel", -- Geneticist Flamel Card
	[4673] = "카드alphoccio", -- Maestro Alphoccio Card
	[4683] = "카드trentini", -- Wanderer Trentini Card
	[4675] = "카드margaretha", -- Arch Bishop Margaretha Card
	[4677] = "카드howard", -- Mechanic Howard Card
	[4678] = "카드kathryne", -- Warlock Kathryne Card
	[4680] = "카드randel", -- Royal Guard Randel Card
	[4671] = "카드celia", -- Sorcerer Celia Card
	[4672] = "카드chen", -- Sura Chen Card
	[4682] = "카드gertie", -- Shadow Chaser Gertie Card
	[27346] = "카드muspell", -- Firm Muspell Card
	[4674] = "카드eremes", -- Guillotine Cross Eremes Card
	[4676] = "카드cecil", -- Ranger Cecil Card
	[4679] = "카드seyren", -- Rune Knight Seyren Card
	[27383] = "카드pandarais", -- Phantom of Amdarais Card
	[27363] = "카드pdl", -- Polluted Dark Lord Card
	[27362] = "카드pqs", -- Polluted Queen Spider Card
	[27381] = "카드phimmel", -- Phantom of Himmelmez Card
	[300100] = "카드gpapilia", -- Gran Papilia Card
	[300007] = "카드jungoliant", -- Jewel Ungoliant Card
	[300151] = "카드akraken", -- Abysmal Kraken Card
	[300145] = "카드awitch", -- Abysmal Witch Card
	[300013] = "카드reginleif", -- Reginleif Card
	[300014] = "카드ingrid", -- Ingrid Card
	[300021] = "카드bdetale", -- Bone Detardeurus Card
	[300280] = "카드bmot", -- Broken Memory of Thanatos Card
	[300382] = "카드aquila", -- Aquila Card
	[300217] = "카드fang", -- Burning Fang Card
	[300281] = "카드rrbestia", -- R001-Bestia Card
	[300378] = "카드juncea", -- Simulation Juncea Card
	[300472] = "카드lasgand", -- Ultimate Lasgand Card
	[300471] = "카드slug", -- Fallen Angel Slug Card
	[300175] = "카드ucreature", -- Unidentified Creature Card
	[300176] = "카드ulifeform", -- Unidentified Life Form Card
	[300473] = "카드angel", -- Snowstorm Angel Card
	[300192] = "카드sakray", -- Sakray Card
	[300193] = "카드tiara", -- Tiara Card
	[300262] = "카드theone", -- The One Card
	[300377] = "카드limacina", -- Ultra Limacina Card
	[300474] = "카드scchief", -- Sanctuary Cleaning Chief Card
	[300297] = "카드gking", -- Goblin King Card
	[300248] = "카드dwitch", -- Death Witch Card
	[300445] = "카드gaiapol", -- Gaia Pol Card
	[300450] = "카드renire", -- Renire Card
}